### ISSUE TITLE
time is not synchronized

### ISSUE THREAD

**Issue by dvbgsmpc** [bebawy6/EPG#1]
time is not synchronized between some channels.
For example between MBC 2 and Bein Movies 1, you need to adjust the offset to one hour !

**Comment by bebawy6** [comment]
Hello there,

I just checked the two channels you provide as example and EPG time for both are synchronized correctly for my provider.
if the EPG is not synchronized correctly for your provider (delayed stream) you can adjust the EPG time offset on your player app (ex. Tivimate).

**Comment by dvbgsmpc** [comment]
Hello, I can adjust this offset globally, but not channel by channel! I am sure that there is a problem in the time

**Comment by bebawy6** [comment]
I am sorry for the inconvenience but it works perfectly on my end, I use Tivimate, it is a kind of expensive app but you can adjust the time offset per channel, per group, or global per playlist.

**Comment by dvbgsmpc** [comment]
Hello, please look at the attached files and double check the name of the movie in the top, and the EPG details in the bottom
![BeinMovies2](https://user-images.githubusercontent.com/25041350/188260649-21f1a4a3-c5c8-4a9d-8550-af48ca8cb3fa.png)
![MBC2](https://user-images.githubusercontent.com/25041350/188260650-2ccd7165-e434-4463-a337-6c59eb34c3d0.png)

**Comment by bebawy6** [comment]
maybe I have an explanation for that, I am on the east coast in the USA, and the EPG grapped for that time, if you live in a different time zone that will be the reason for the time shift.

**Comment by dvbgsmpc** [comment]
The difference of Timezone can be adjusted by the offset globally. The problem here is, even if we adjust that, there is a time shift between some channels. The explanation for me is when you concatenate programs in the EPG the programs have not the same time shift. So you need to fix this time shift before concatenating.

**Comment by bebawy6** [comment]
I confirmed that Bein Movies 2 has one hour shift this morning.
Can you please confirm which channels need that adjust or all the group

**Comment by dvbgsmpc** [comment]
Hi, It is all the group of Bein Movies

**Comment by bebawy6** [comment]
Fixed

**Comment by dvbgsmpc** [comment]
Hello, I still got the same problem. 
![Capture d’écran 2022-09-04 112521](https://user-images.githubusercontent.com/25041350/188306693-c3e9ffe4-2b05-4a1e-883e-5e3a50e08c64.png)

**Comment by dvbgsmpc** [comment]
Hello again,

I found how to fix the issue. in the line below you need to change the offset from +0400 to +0500
  <programme start="20220904121500 +0400" stop="20220904144500 +0400" channel="BeIN Movies 2 4K">
So you need to do this for the whole group (search for +0400" channel="beIN)

Also the same problem for Egypt channels. (search for -0300" channel="Eg:), you need to change the -0300 by +0400

I will give you the other fixes to do when I find other ones ;)

**Comment by bebawy6** [comment]
Hello There,
the way it work as in the attached picture I grab the EPG first using encrypted ini file I can not edit (from payed provider) then apply a selected channel time modify
Bein ent. group fixed still work on Egypt for 1 hour
![Untitled](https://user-images.githubusercontent.com/71897043/188329310-26bb556a-efd3-4ae9-b326-e4e9b6512353.png)
![Capture2](https://user-images.githubusercontent.com/71897043/188329570-65a3d4ae-35f8-4c86-826e-f346f5a4bac6.JPG)

**Comment by dvbgsmpc** [comment]
Hello,
Bein Movies for me is not fixed yet, you need to shift the time by -2hours

**Comment by bebawy6** [comment]
Hello there,

see attached it is working now for the Bein, please try to reset your global setting don't add the 2 hours, your program should take care of that, clear your cashes and clear EPG and refresh it and try.

I think is pretty clear, as always depends if your app convert or not, the EPG.xml to the local time.

please advise what is the app name you use

http://webgrabplus.com/documentation

![2022_09_04 12_44 PM Office Lens](https://user-images.githubusercontent.com/71897043/188331992-c8e6454f-4587-4eac-8a9e-499cafaffb1e.jpg)
![2022_09_04 12_53 PM Office Lens](https://user-images.githubusercontent.com/71897043/188331993-77b1c8de-d733-481e-b13a-114a29bf487e.jpg)
![2022_09_04 12_51 PM Office Lens](https://user-images.githubusercontent.com/71897043/188331994-84a71e09-d216-4181-8652-94ba332f0442.jpg)

**Comment by dvbgsmpc** [comment]
Hello,
I am using SimpleTV. Now I changed the global offset to +0h and as I guessed:
MBC is not OK,  you should change it to +2H
BEIN is OK

The logic says, I should keep the offset to +2H as I live in UTC+2 and you should use the correct offset depending on your timezone and fix all channels using the correct global offset.

**Comment by bebawy6** [comment]
I am in UTC-8, I didn't adjust the time to my local time, just grab the EPG and the app corrected, for Bein sport the ini file used set to AbuDabi local time which is not observing daytime saving time that is why it needed the 1 hour correction.

**Comment by dvbgsmpc** [comment]
Thank you for sharing, but I wanted it to be fixed from your side. Thank you for your time
